# Generated by Django 5.1.6 on 2025-07-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliateproduct",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="affiliateproduct",
            name="link",
        ),
        migrations.RemoveField(
            model_name="affiliateproduct",
            name="source",
        ),
    ]
