# Generated by Django 5.1.6 on 2025-07-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0003_giftuser_loginlog_delete_myuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
