apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: wrapzy
type: Opaque
stringData:
  DJANGO_SECRET_KEY: X2t21=e2%gCuQY_YqK5fqA7CLmcNdf2ZVI(vJcIdca*0nm66Sc
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "0098"