apiVersion: apps/v1
kind: Deployment

metadata:
  name: django
  namespace: wrapzy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: django

  template:
    metadata:
      labels:
        app: django

    spec:
      containers:
        - name: django
          image: prapanjanprabhu/wrapzy:v4
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY

            - name: DB_NAME
              value: "one"

            - name: DB_USER
              value: "django"

            - name: DB_PASSWORD
              value: "0098"

            - name: DB_HOST
              value: "mysql-service"

            - name: DB_PORT
              value: "3306"
            - name: DJANGO_DEBUG
              value: "False"

            - name: DJANGO_ALLOWED_HOSTS
              value: "*"

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ADMIN_USERNAME

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ADMIN_PASSWORD

          command: ["sh", "-c"]

          args:
            - python manage.py migrate && python manage.py runserver 0.0.0.0:8000